services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:application --host 0.0.0.0 --port 8000 --reload"

volumes:
  my_db:
